/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("StickerMasterObjectPageObjectPage journey");

        opaTest("Navigate to StickerMasterObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheStickerMasterListGenerated.onFilterBar().iExecuteSearch();

            Then.onTheStickerMasterListGenerated.onTable().iCheckRows();
            When.onTheStickerMasterListGenerated.onTable().iPressRow(0);

            Then.onTheStickerMasterObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            // Ensure the opened entity is not in Draft state before uncommenting
            // Then.onTheStickerMasterObjectPageGenerated.onHeader().iCheckEdit({ visible: true });
            // When.onTheStickerMasterObjectPageGenerated.onHeader().iPressEdit();
            Then.onTheStickerMasterObjectPageGenerated.onHeader().iCheckAction("Reject Request" /* , { enabled: true } */);
            // When.onTheStickerMasterObjectPageGenerated.onHeader().iPressAction("Reject Request");
            Then.onTheStickerMasterObjectPageGenerated.onHeader().iCheckAction("Approve Request" /* , { enabled: true } */);
            // When.onTheStickerMasterObjectPageGenerated.onHeader().iPressAction("Approve Request");
            Then.onTheStickerMasterObjectPageGenerated.onHeader().iCheckAction("Reschedule" /* , { enabled: true } */);
            // When.onTheStickerMasterObjectPageGenerated.onHeader().iPressAction("Reschedule");
        });

        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheStickerMasterObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "Status" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheStickerMasterObjectPageGenerated.iCheckNumberOfSections(3);
            When.onTheStickerMasterObjectPageGenerated.iPressSectionIconTabFilterButton("GeneralInfo");
            Then.onTheStickerMasterObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            When.onTheStickerMasterObjectPageGenerated.iPressSectionIconTabFilterButton("VehicleDetails");
            Then.onTheStickerMasterObjectPageGenerated.iCheckSection({ section: "VehicleDetails" });
            When.onTheStickerMasterObjectPageGenerated.iPressSectionIconTabFilterButton("AppointDetails");
            Then.onTheStickerMasterObjectPageGenerated.iCheckSection({ section: "AppointDetails" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});