/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("StickerMasterListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheStickerMasterListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheStickerMasterListGenerated.onFilterBar().iCheckFilterField("SMS Request No.");
            Then.onTheStickerMasterListGenerated.onFilterBar().iCheckFilterField("Type of Request");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheStickerMasterListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheStickerMasterListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheStickerMasterListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheStickerMasterListGenerated.onTable().iCheckCreate({ visible: true });
            // Then.onTheStickerMasterListGenerated.onTable().iPressCreate();
            // Then.onTheStickerMasterListGenerated.onTable().iPressDelete();
            Then.onTheStickerMasterListGenerated.onTable().iCheckDelete({ visible: true });
            // Then.onTheStickerMasterListGenerated.onTable().iPressAction("Copy Request");
            Then.onTheStickerMasterListGenerated.onTable().iCheckAction("Copy Request", { enabled: false });
            Then.onTheStickerMasterListGenerated.onTable().iCheckColumns(undefined, {"StkReqIdStr":{"header":"SMS Request No."},"StkType":{"header":"Type of Request"},"ArabicName":{"header":"Requestor Name"},"Name":{"header":"Requestor Name"},"VendorName":{"header":"Vendor Name"},"LocationDesc":{"header":"Location"},"Status":{"header":"Status"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheStickerMasterListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheStickerMasterListGenerated.onTable().iCheckRows();

            When.onTheStickerMasterListGenerated.onTable().iPressRow(0);
            Then.onTheStickerMasterObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});